### ISSUE TITLE
support for specifying IDNA domains as utf-8 in config file

### ISSUE THREAD

**Issue by florianjacob** [kanla/kanla#22]
Currently, an [IDNA](https://en.wikipedia.org/wiki/Internationalized_domain_name) domains like http://日本語.jp/ (actually exists) or http:/dömain.example/ need to be specified as IDNA encoded http://xn--wgv71a119e.jp/ to make kanla able to resolve them.

If you enter utf-8 directly, the current result is:
```
Cannot resolve A DNS record for æ¥æ¬èª.jp
Cannot resolve AAAA DNS record for æ¥æ¬èª.jp
```

**Comment by stapelberg** [comment]
Can you please send a PR to fix this? I personally don’t need the feature and am short on time.
